# DATA TYPES

In [1]:
a=10

In [2]:
type(a)

int

In [3]:
b=10.35

In [4]:
type(b)

float

In [5]:
c="12.45"

In [6]:
type(c)

str

In [7]:
c="Hello"

In [8]:
type(c)

str

In [9]:
c

'Hello'

In [10]:
c=""

In [11]:
bool(c)

False

In [12]:
b=" "

In [13]:
bool(b)

True

In [ ]:
#Python Datatypes
#Lists , Tuples , Strings ,Dictionaries , Sets
#list=[]
#Collection of arrays
#Mutable

In [14]:
x=[]

In [15]:
type(x)

list

In [16]:
print(x)

[]


In [17]:
#add first element
x.append(100)

In [18]:
print(x)

[100]


In [19]:
x.append(20,56)

TypeError: append() takes exactly one argument (2 given)

In [20]:
x.extend(20,56)

TypeError: extend() takes exactly one argument (2 given)

In [21]:
x.extend([100,3.45,'List'])

In [22]:
x

[100, 100, 3.45, 'List']

In [23]:
x.pop()

'List'

In [28]:
x.reverse()

In [29]:
x

[100, 100, 3.45]

In [31]:
x.reverse()

In [32]:
x

[100, 100, 3.45]

In [33]:
x=[100,10,12]

In [34]:
x

[100, 10, 12]

In [35]:
x.reverse()
x

[12, 10, 100]

In [36]:
#sorting
x.sort()
x

[10, 12, 100]

In [37]:
x=[100,100,'string']

In [38]:
x.sort()

TypeError: '<' not supported between instances of 'str' and 'int'

x.count(100)

In [40]:
x.remove('string')

In [41]:
x

[100, 100]

In [42]:
x.insert(2,200)

In [43]:
x

[100, 100, 200]

In [44]:
x.index(2)

ValueError: 2 is not in list

In [45]:
x.index(100)

0

# 2D ARRAY

In [46]:
y=[[100,200],[300,400]]

In [47]:
y

[[100, 200], [300, 400]]

c0    c1
[100  200]r0
[300  400]r1
[r][c]

In [49]:
y[0]

[100, 200]

In [50]:
y[0][1]

200

In [53]:
b=[12,3,[24,'list',46],[100,4500,56]]

In [54]:
b[3][0]

100

In [55]:
b.extend(([123,90,[12.45],56],'python','string'))

In [56]:
b

[12,
 3,
 [24, 'list', 46],
 [100, 4500, 56],
 [123, 90, [12.45], 56],
 'python',
 'string']

In [57]:
b[0]

12

In [58]:
b[4][2]

[12.45]

In [59]:
b[4][2][0]

12.45

In [60]:
b[3][1]=450

In [61]:
b

[12,
 3,
 [24, 'list', 46],
 [100, 450, 56],
 [123, 90, [12.45], 56],
 'python',
 'string']

In [67]:
b.insert(6,[12,24,45.67])
b

[12,
 3,
 [24, 'list', 46],
 [100, 450, 56],
 [123, 90, [12.45], 56],
 'python',
 [12, 24, 45.67],
 [12, 45, 57]]

In [68]:
b[7]='string'
b

[12,
 3,
 [24, 'list', 46],
 [100, 450, 56],
 [123, 90, [12.45], 56],
 'python',
 [12, 24, 45.67],
 'string']

# NUMPY

In [69]:
!pip install numpy

In [70]:
import numpy

In [73]:
z=[100,200]

In [74]:
numpy.add(y,z)

array([[200, 400],
       [400, 600]])

In [75]:
numpy.multiply(y,z)

array([[10000, 40000],
       [30000, 80000]])

In [76]:
import numpy as np

In [80]:
from numpy import add,multiply,subtract

In [81]:
numpy.subtract(y,z)

array([[  0,   0],
       [200, 200]])

In [82]:
from numpy import * 
#to access all methods

In [83]:
sum(y)

1000

In [84]:
divide(y,z)

array([[1., 1.],
       [3., 2.]])

In [85]:
y

[[100, 200], [300, 400]]

In [89]:
#tuple
#orederable,iterable,immutable,use multiple datatypes
a=([12,45],'Tuple',24,3425.5,(415))

In [87]:
type(a)

tuple

In [88]:
#tuple operations -index, count
a.count(12)

0

In [90]:
a.index(24)

2

In [91]:
type(a[0])

list

In [92]:
a

([12, 45], 'Tuple', 24, 3425.5, 415)

In [93]:
#([12, 45], 'Tuple', 24, 3425.5, 415)
a[0].insert(0,123)

In [94]:
a

([123, 12, 45], 'Tuple', 24, 3425.5, 415)

In [95]:
x=(100)

In [96]:
x

100

In [97]:
type(x)

int

In [98]:
y=(100,)
y

(100,)

In [99]:
type(y)

tuple

In [103]:
y=([23,45,345,'string',4.45],)
y

([23, 45, 345, 'string', 4.45],)

In [104]:
type(y)

tuple

In [105]:
y[1]

IndexError: tuple index out of range

In [106]:
type(y[0])

list

In [107]:
y[0].remove('string')

In [108]:
y

([23, 45, 345, 4.45],)

In [109]:
#string-'',"",''''''
#oredrable,iterable,immutable,use multiple datatypes
a='str'

In [110]:
type(a)

str

In [111]:
z='(345,56,354.56)'

In [112]:
c="hello world"

In [113]:
c.capitalize()

'Hello world'

In [114]:
c.upper()

'HELLO WORLD'

In [115]:
c.lower()

'hello world'

In [116]:
c.split()

['hello', 'world']

In [117]:
c.startswith('H')

False

In [118]:
c.startswith('h')

True

In [119]:
c.endswith('d')

True

In [120]:
c.center(25)

'       hello world       '

In [121]:
c.center(25,'*')

'*******hello world*******'

In [122]:
y='    String Data    '

In [123]:
y

'    String Data    '

In [124]:
y.strip()

'String Data'

In [126]:
#string slicing(Included:Excluded)
x='String data'

In [127]:
x[0:6]

'String'

In [128]:
x[0:5]

'Strin'

In [129]:
x[0:3]

'Str'

In [130]:
x[:3]

'Str'

In [131]:
x[:]

'String data'

In [132]:
#last index:-1
x[7:-1]

'dat'

In [133]:
x[7:]

'data'

In [134]:
x="Hello world"

In [135]:
x[:4]

'Hell'

In [136]:
x[6:-2]

'wor'

In [138]:
x[::2]#skip one letter (intermediate characters)

'Hlowrd'

In [139]:
x[::3]#skip 2 letters

'Hlwl'

In [141]:
x[::-1]#reversing contents

'dlrow olleH'

In [142]:
y='References'

In [143]:
#Refer
y[0:5]

'Refer'

In [145]:
#Rens
y[::3]

'Rens'

In [146]:
#rence
y[4:9]

'rence'

In [147]:
#user defined variables
a=input("Enter a:")

Enter a:56


In [148]:
type(a)

str

In [4]:
#user defined variables
b=int(input("Enter b:"))

Enter b:79


In [5]:
type(b)

int

In [6]:
#user defined variables
ic=input("Enter a:")

Enter a:123


In [2]:
x=input("Enter value of x: ")
print("x value is {}",format(x))

Enter value of x: 123
x value is {} 123


In [5]:
x=3
a='8'
print("x value is {} and a value is {}",format(x,a))

x value is {} and a value is {}        3


# DICTIONARY - {KEY:VALUE}
# UNORDERED, ITERABLE, MUTABLE,ALLOWS MULTIPLE DATATYPES

In [23]:
y={'id':90,'name':'anu'}

In [24]:
y

{'id': 90, 'name': 'anu'}

In [25]:
y['college']='rns'

In [26]:
y

{'id': 90, 'name': 'anu', 'college': 'rns'}

In [27]:
y.keys()

dict_keys(['id', 'name', 'college'])

In [28]:
y.values()

dict_values([90, 'anu', 'rns'])

In [29]:
y['college']

'rns'

In [6]:
x={'id':[10,20,40,5],'domain':('python','data science')}

In [7]:
x

{'id': [10, 20, 40, 5], 'domain': ('python', 'data science')}

In [8]:
x['id'][3]

5

In [9]:
x['domain'][1]

'data science'

In [10]:
x.update({'places':['blr',('chennai',['mum','pune'])]})

In [11]:
x

{'id': [10, 20, 40, 5],
 'domain': ('python', 'data science'),
 'places': ['blr', ('chennai', ['mum', 'pune'])]}

In [12]:
#pune
x['places'][1][1][1]

'pune'

In [14]:
x.update({"10":{'name':'karthik','domains':['ai','it']},"branch":['cs','it']})

In [15]:
x['branch'][1]

'it'

In [16]:
x.keys()

dict_keys(['id', 'domain', 'places', '10', 'branch'])

In [17]:
x['10'].keys()

dict_keys(['name', 'domains'])

# DATAFRAME 

In [6]:
#dataframe - multidimensional array
!pip install pandas
import pandas as pd

In [2]:
y={'area':[1000,2000,3000,4000],'price':[1000,2000,3000,4000]}

In [3]:
y

{'area': [1000, 2000, 3000, 4000], 'price': [1000, 2000, 3000, 4000]}

In [7]:
df=pd.DataFrame(y)

In [8]:
df

area  price
0  1000   1000
1  2000   2000
2  3000   3000
3  4000   4000

In [9]:
y.get('area')

[1000, 2000, 3000, 4000]

In [10]:
y.get('areas','key not found')

'key not found'

In [11]:
df.to_csv("Price.csv")

In [12]:
df.to_excel("Price.xlsx")

In [13]:
test_dict={'r1':[1,2,3,4],'r2':[5,6,7,8],'r3':[9,10,11,12]}

In [14]:
test_dict

{'r1': [1, 2, 3, 4], 'r2': [5, 6, 7, 8], 'r3': [9, 10, 11, 12]}

In [15]:
df.to_json

<bound method NDFrame.to_json of    area  price
0  1000   1000
1  2000   2000
2  3000   3000
3  4000   4000>

# SETS

In [24]:
#Set={}
#mapping process
#unordered,doen't allow repeated values,mutable,iterable,multiple data types

In [18]:
x={"python","ai",23.5,34}

In [19]:
y={23.5,'c',7}

In [20]:
x

{23.5, 34, 'ai', 'python'}

In [21]:
y

{23.5, 7, 'c'}

In [22]:
type(x)

set

In [23]:
type(y)

set

In [26]:
y | x #or operator

{23.5, 34, 7, 'ai', 'c', 'python'}

In [27]:
y & x

{23.5}

In [28]:
34 in x or y

True

In [29]:
x.discard(34)

In [30]:
x

{23.5, 'ai', 'python'}

In [31]:
x={'ID':10}
y={'Branch':'CS'}

In [32]:
y.update(x)

In [33]:
y

{'Branch': 'CS', 'ID': 10}

# Conditional Statements

In [2]:
#conditional statement 
#if,else,elif
#positive,even,palindrome,greatest of 3 numbers
a=int(input("Enter a: "))
#if expr
if a>0:
    #indentation space
    b=a**2
    print("Positive value is ",a,"and square data ",b)
elif a==0:
    pass
else:
    b=a**3
    print("Negative value is ",a,"cube data ",b)

Enter a: 0


In [3]:
#even or odd number
a=int(input("Enter a: "))
if a%2==0:
    print("Even number")
elif a==0:
    pass
else:
    print("Odd number")

Enter a: 12
Even number


In [5]:
#string palindrome
x="refer"
if x==x[::--1]:
    print("Palindrome")
else:
    print("Not palindrome")

Palindrome


In [7]:
#looping statement
#for iter_var in seq:
x=[10,20,30,40,50]

In [8]:
for num in x:
    print(x)

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]


In [9]:
for num in x:
    print(num)

10
20
30
40
50


In [11]:
x.pop()#executed twice.
x
for i in x:
    print(i/2)

5.0
10.0
15.0


In [12]:
#[i:e]
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [14]:
#1*10=10
t=int(input("Enter table no.: "))
e=int(input("Enter last range: "))
for i in range(1,e):
    print(i,"*",t,"=",i*t)

Enter table no.: 10
Enter last range: 6
1 * 10 = 10
2 * 10 = 20
3 * 10 = 30
4 * 10 = 40
5 * 10 = 50


In [16]:
for i in range(1,5):
    if i%2==0:
        print(i,"Is Even")
        break
    else:
        print(i,"Is Odd")

1 Is Odd
2 Is Even


In [19]:
for i in range(1,10):
    if 10%i==0:
        print(i,"Is a prime number")
    else:
        print(i,"Is not a prime number")

1 Is a prime number
2 Is a prime number
3 Is not a prime number
4 Is not a prime number
5 Is a prime number
6 Is not a prime number
7 Is not a prime number
8 Is not a prime number
9 Is not a prime number


In [22]:
#prime or not prime
for i in range(11,16):
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:
            print(i)

11
13


In [24]:
i=1
while i<6:
    i=i+2
    print(i)

3
5
7


In [25]:
#function:
#def fn_name():
def add(a=90,b=10):
    return a+b

In [26]:
#calling function
add()

100

In [27]:
add(100,200)

300

In [28]:
def srq(a):
    print(a**2)

In [29]:
srq(10)

100


In [31]:
x=int(input("Enter x: "))
def cube(x):
    return x**3
cube(x)

Enter x: 2


8

In [32]:
def empty():
    print("Empty Function")
empty()

Empty Function


In [33]:
x=100 #global

In [34]:
def var():
    x=200
    print(x)

In [35]:
x

100

In [36]:
def add():
    global x
    y=x+200
    print(y)
add()

300


In [40]:
#Anonymous Function- Lambda
#lamda var:expr
y=lambda a,b:a+b
z=lambda a,b,c:(a+b+c)/3
z(10,20,30)

20.0

In [38]:
y(12,34)

46

In [41]:
n=[30,23,4,33,1,8]
c=filter(lambda x:(x%2==0),n)

In [42]:
list(c)

[30, 4, 8]

In [43]:
def even(n):
    if n%2==0:
        return True
    return False

In [44]:
y=filter(even,n)
list(y)

[30, 4, 8]

# OOPS

In [59]:
#CLASS-user-defined prototype or blueprint of an object
#class clsname - 2 properties-attribute and behavior
class Student:
    def __init__(self,college):
        print("College: ",college)
    #Methods-Similar to function
    def details(self,name,course):
        #self is used to access the attributes or behavior var value
        print("Name: ",name)
        print("Course: ",course)
    def perform(x,grade):
        print("Rank: ",grade)
obj=Student("RNSIT")
obj.details("Deethya","ISE")

College:  RNSIT
Name:  Deethya
Course:  ISE


In [58]:
#Object-Instance of the class
s=Student()

College: 


In [51]:
s.details("Preethu","CS")

Name:  Preethu
Course:  CS


In [54]:
s1=Student()
s1.details("Karthik","IT")
s1.perform("A")

RNSIT
Name:  Karthik
Course:  IT
Rank:  A


In [63]:
#Inheritance-Base class and Derived class
#Derived class can access base cls properties
#base class can't access derived class properties
#single Inheritance-1 base class and 1 derived class
class college:#Base class
    def __init__(self,college):
        print("College: ",college)
    #Methods-Similar to function
class Student(college):#Derived class
    def details(self,name,course):
        #self is used to access the attributes or behavior var value
        print("Name: ",name)
        print("Course: ",course)
    def perform(x,grade):
        print("Rank: ",grade)
obj=Student("RNSIT")
obj.details("Deethya","ISE")

College:  RNSIT
Name:  Deethya
Course:  ISE


In [64]:
#Inheritance-Base class and Derived class
#Derived class can access base cls properties
#base class can't access derived class properties
#Multiple Inheritance-1 base class and Multiple derived class
class college:#Base class
    def __init__(self,college):
        print("College: ",college)
    #Methods-Similar to function
class Student(college):#Derived class
    def details(self,name,course):
        #self is used to access the attributes or behavior var value
        print("Name: ",name)
        print("Course: ",course)
class marks(Student):
    def perform(x,grade):
        print("Rank: ",grade)
obj=Student("RNSIT")
obj.details("Deethya","ISE")
obj1=marks("A")

College:  RNSIT
Name:  Deethya
Course:  ISE
College:  A


In [65]:
#Multiple Inheritance
class Add:#Base class
    def add(x,a,b):
        print(a+b)
class Sub:#Base class
    def sub(x,a,b):
        print(a-b)
class Mul:#Base class
    def mul(x,a,b):
        print(a*b)
class Div(Add,Sub,Mul):
    def div(x,a,b):
        print(a/b)

In [67]:
d=Div()
d.add(12,3)
d.sub(12,3)
d.div(12,3)
d.mul(12,3)

15
9
4.0
36


In [68]:
import math

In [69]:
math.cos(12)

0.8438539587324921

In [74]:
#Data Encapsulation-Hide the values
#_- to hide the data 
class Product:
    price=1100
    __price=1200#hidden data

In [75]:
p=Product()
p.price

1100

In [76]:
#obj._cls_name_hiddenvar
p._Product__price

1200

In [1]:
#Polymorphism-overriding the data or many forms
class Add:#Base class
    def add(x,a,b):
        print(a+b)
class Sub:#Base class
    def sub(x,a,b):
        print(a-b)
class Mul:#Base class
    def mul(x,a,b):
        print(a*b)
class Div(Add,Sub,Mul):#Derived class
    def add(x,a,b):
        print(a/b)
    def add(x):
        print("Add")

In [2]:
d=Div()
d.add()

Add


In [4]:
a=int(input("Enter price: "))
if a<=1000:
    dis=1000*0.01
    tot=a-dis
    print("Total: ",tot)
else:
    pass

Enter price: 999
Total:  989.0


# ASSIGNMENT DAY-1

In [7]:
# 1. Finding greatest of three numbers
x = int(input("Enter value of x:"))
y = int(input("Enter value of y:"))
z = int(input("Enter value of z:"))

if x>=y and x>=z:
    L=x
elif y>=x and y>=z:
    L=y
else:
    L=z

print("The greatest of the three numbers is: "+str(L))

Enter value of x:20
Enter value of y:30
Enter value of z:50
The greatest of the three numbers is: 50


In [9]:
# 2. if a<=1000(give a discount of 10%),a<=2000(give a discount of 20%),a<=3000(give a discount of 30%)
a = int(input("Enter the price of the item: "))
if a<=1000:
    a=a-(a*0.10)
    print("The Discounted price of a is ",format(a))
    
elif a<=2000:
    a=a-(a*0.20)
    print("The Discounted price of a is ",format(a))
    
elif a<=3000:
    a=a-(a*0.30)
    print("The Discounted price of a is",format(a))
    

Enter the price of the item: 1500
The Discounted price of a is  1200.0


In [11]:
# 3. Using For loop Find the Factorial of a number

x = int(input("Enter a number: "))
fact = 1
if x<0:
    print("Negative numbers do not have a factorial. Please Enter a positive number.")
elif x==0:
    print("The factorial of the given number 0 is 1")
else:
    for i in range(1,x+1):
        fact=fact*i
    print("The factorial of the given number {x} is: "+str(fact))

Enter a number: 5
The factorial of the given number {x} is: 120


In [12]:
# 4. Fibonacci series (using for loop)

n = int(input("Till how many terms do you want to calculate the fibonacci series? "))

n1, n2 = 0, 1
if n<=0:
    print("Enter a positive number: ")
elif n==1:
    print(f"The Fibonacci series up to {n} is {n1}")
else:
    print("The Fibonacci series is: ")
    for i in range(n+1):
        print(n1, end=' ')
        n0=n1+n2
        n1=n2
        n2=n0

Till how many terms do you want to calculate the fibonacci series? 5
The Fibonacci series is: 
0 1 1 2 3 5 

In [13]:
# 5. Sum of first n numbers

n= int(input("Enter the value of n: "))
nos=n
if n<0:
    print("Enter a positive number: ")
else:
    sum=0
    while(n>0):
        sum +=n
        n-=1
    print(f"The sum of first {nos}"+" numbers is",sum)

Enter the value of n: 8
The sum of first 8 numbers is 36


In [14]:
# 6. Reverse a number using while

n = int(input("Enter a number to be reversed: "))
rev_n = 0
while n!=0:
    i=n%10
    rev_n = rev_n*10+i
    n//=10
    
print("The reversed number is : ",rev_n)

Enter a number to be reversed: 1228
The reversed number is :  8221


In [15]:
# 7. To Check if a number is an armstrong number or not

n = int(input("Enter a number: "))
sum=0
temp=n
while temp>0:
    i=temp%10
    sum+=i**3
    temp//=10
if n==sum:
    print(f"{n} is an Armstrong number")
else:
    print(f"{n} is not an Armstrong number")

Enter a number: 153
153 is an Armstrong number


In [17]:
#8.Python program to print the following pattern
#*
#**
#***
#****
#*****
def pypart(n):
    for i in range(0, n):
        for j in range(0, i+1):
            print("* ",end="")
        print("\r")
n=5
pypart(5)

* 
* * 
* * * 
* * * * 
* * * * * 
